### ISSUE TITLE
Bitmovin not working in  angular 2+

### ISSUE THREAD

**Issue by PaulCheriyan009** [bitmovin/bitmovin-player-web-samples#14]
Bitmovin not working in  angular 2+, I have used npm to install bitmovin.

>   npm i bitmovin-player

the code i user are as follow
`  
import * as bitmovin from 'bitmovin-player'
const conf = {
      key: 'c0e00b92-8710-4767-8ba6-97fe45b45135',
     
      source: {
      dash: 'https://testorigin.cinesoft.live/freedrmvod/smil:Billa_2.smil/manifest.mpd',
     //  hls: '********************************',
      drm: {
      widevine : {
      LA_URL: '******************************',
      headers: [{
      name: 'utoken-drm',
      value: 'wv'
      }],
      prepareMessage : function(keyMessage) {
      return keyMessage.message;
      }
      },
      prepareLicense: function(license) {
      return new Uint8Array(license);
      },
      headers: [{
      name: 'Content-type',
      value: 'application/octet-stream'
      },
      {
      name: 'utoken-drm',
      value: 'fp'
      }],
      useUint16InitData: true,
      licenseResponseType: 'arraybuffer'
      }
      } // end drm
      } // end source
      // tslint:disable-next-line:prefer-const
      let videoplayer;
      bitmovin(this.videoElement.nativeElement).setup(conf).then(function(playerInstance) {
         console.log('Successfully created Bitmovin Player instance');
       }, function(reason) {
         console.log('Error while creating Bitmovin Player instance');
       });`

bitMovin version used 

> "bitmovin-player": "^7.6.3",
pl

**Comment by pajics** [comment]
Hi Paul,

I just tried and it works for me.
Here are the steps I took:

- Add it as dependancy to the project _npm i bitmovin-player --save_

- bitmovin already has typescript definitions, so you can use it directly in angular. Here is an example of PlayerComponent (based on bitmovin tutorial found here: https://bitmovin.com/docs/player/quickstarts/get-started-with-the-bitmovin-player)
`import { Component, AfterViewChecked } from '@angular/core';
import { Player } from 'bitmovin-player';

@Component({
  selector: 'app-player',
  templateUrl: './player.component.html'
})

export class PlayerComponent implements AfterViewChecked {
  ngAfterViewChecked() {
    setTimeout(() => {
      const container = document.getElementById('my-player');
      const playerConfig = {
        key: '945cf862-d48e-4f07-94a5-aeaa67969bfd'
      };
      const source = {
        title: 'Getting Started with the Bitmovin Player',
        description: 'Now you are ready to embed the Bitmovin Player into your own website :)',
        dash: 'https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd',
        hls: 'https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8',
        progressive: 'https://bitmovin-a.akamaihd.net/content/MI201109210084_1/MI201109210084_mpeg-4_hd_high_1080p25_10mbits.mp4',
        poster: 'https://bitmovin-a.akamaihd.net/content/MI201109210084_1/poster.jpg'
      };
      const player = new Player(container, playerConfig); // const player = new bitmovin.player.Player(container, playerConfig);

      player.load(source).then(
        play => {
          console.log('Successfully created Bitmovin Player instance')
        },
        reason => {
          console.log('Error while creating Bitmovin Player instance')
        }
      );
    }, 3000);
  }
}`


html code:
<div id="my-player"></div>

**Comment by PaulCheriyan009** [comment]
Hi Srdjan,
               Thank You for your help

On Tue, Oct 23, 2018 at 7:08 PM Srdjan Pajic <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Paul,

I just tried and it works for me.
Here are the steps I took:

  *   Add it as dependancy to the project npm i bitmovin-player --save

  *   bitmovin already has typescript definitions, so you can use it directly in angular. Here is an example of PlayerComponent (based on bitmovin tutorial found here: https://bitmovin.com/docs/player/quickstarts/get-started-with-the-bitmovin-player)

`
import { Component, AfterViewChecked } from '@angular/core';
import { Player } from 'bitmovin-player';

@component<https://github.com/component>({
selector: 'app-player',
templateUrl: './player.component.html'
})

export class PlayerComponent implements AfterViewChecked {
ngAfterViewChecked() {
setTimeout(() => {
const container = document.getElementById('my-player');
const playerConfig = {
key: '945cf862-d48e-4f07-94a5-aeaa67969bfd'
};
const source = {
title: 'Getting Started with the Bitmovin Player',
description: 'Now you are ready to embed the Bitmovin Player into your own website :)',
dash: 'https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd',
hls: 'https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8',
progressive: 'https://bitmovin-a.akamaihd.net/content/MI201109210084_1/MI201109210084_mpeg-4_hd_high_1080p25_10mbits.mp4',
poster: 'https://bitmovin-a.akamaihd.net/content/MI201109210084_1/poster.jpg'
};
const player = new Player(container, playerConfig); // const player = new bitmovin.player.Player(container, playerConfig);
player.load(source).then(
play => {
console.log('Successfully created Bitmovin Player instance')
},
reason => {
console.log('Error while creating Bitmovin Player instance')
}
);
}, 3000);
}
}`

html code:
<div id="my-player"></div>

**Comment by dweinber** [comment]
Seems this issue was resolved, I'm going to close this ticket.
