### ISSUE TITLE
Playlist Example Error

### ISSUE THREAD

**Issue by josephlodero** [bitmovin/bitmovin-player-web-samples#22]
Hi. i have these error every time the next video is loaded 
![image](https://user-images.githubusercontent.com/11495107/45464328-b0fe9900-b742-11e8-9ed9-9e63a7b5d70f.png)

im using Ionic3

**Comment by stonko1994** [comment]
I don't think this is an issue from the sample or even the player. I think it's rather something in your `Ionic3` example. It's working fine for me so i will close this issue.
