### ISSUE TITLE
How to store user settings?

### ISSUE THREAD

**Issue by fatih108** [bitmovin/bitmovin-player-web-samples#29]
Hi..
How to store user settings? 
I found a setting but removed with v8 (restoreUserSettings)..
How can I store the user's volume setting?

**Comment by dweinber** [comment]
@fatih108 we'll provide a sample for that. 

Basically, you need to listen to [`VolumeChanged`](https://cdn.bitmovin.com/player/web/8/docs/enums/core_events.playerevent.html#volumechanged), [`Muted`](https://cdn.bitmovin.com/player/web/8/docs/enums/core_events.playerevent.html#muted) and [`Unmuted`](https://cdn.bitmovin.com/player/web/8/docs/enums/core_events.playerevent.html#unmuted) events and store the values in the browser's [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage).

When you create a new player you check the `localStorage` and set the relevant settings.

**Comment by dweinber** [comment]
As there was no further feedback, I'm going to close this issue.
