### ISSUE TITLE
Player UI hidden in Firefox until playback ends

### ISSUE THREAD

**Issue by tommilimmot** [bitmovin/bitmovin-player-web-samples#31]
Player UI is hidden on Firefox 65.0.1 during video playback. UI appears first time when video playback ends – there is no way to e.g. pause playback during the whole video clip and ads.

Use case:

1. load bitmovinplayer.js
2. initialise player on user interaction
```
const player = bitmovin.player("player");
const playerInstance = player.setup(config);
```
3. start playback on next user interaction
```
playerInstance.load(source);
playerInstance.play();
```

Tested on v7.7.7 and v7.8.14

**Comment by unki2aut** [comment]
This is not an issue with the player samples, please contact support@bitmovin.com for further help.

`player.setup` and `player.load` are async operation so this would need to look something like
```ts
// first user interaction
const player = bitmovin.player("player");
const playerReady = player.setup(config);

// second user interaction
playerReady
  .then(() => player.load(source))
  .then(() => player.play());
```

**Comment by tommilimmot** [comment]
@unki2aut true. But I asked Stephen where I could report issues to and he pointed me here. I already have couple of mail threads running and it's much harder to follow the issues via email.
