### ISSUE TITLE
bitmovin is not defined in v7.8.15 and v7.8.16

### ISSUE THREAD

**Issue by tommilimmot** [bitmovin/bitmovin-player-web-samples#32]
Global bitmovin object is missing in
https://bitmovin-a.akamaihd.net/bitmovin-player/stable/7.8.15/bitmovinplayer.js
https://bitmovin-a.akamaihd.net/bitmovin-player/stable/7.8.16/bitmovinplayer.js

Browser console shows this error
```
bitmovinplayer.js:11 Uncaught SyntaxError: Invalid or unexpected token
```

**Comment by dweinber** [comment]
There was an issue with uploading the files to the CDN, which led to corrupted files. This should be resolved by now.

**Comment by tommilimmot** [comment]
Seems to work again. Thanks @dweinber!
