### ISSUE TITLE
Customizing volume

### ISSUE THREAD

**Issue by lucassouzamiranda** [bitmovin/bitmovin-player-web-samples#33]
Hello,

I'm trying to put the volume upright. I changed the value to true and did not change.

this.config = this.mergeConfig (config, {
       cssClass: 'ui-seekbar',
       vertical: true,
       smoothPlaybackPositionUpdateIntervalMs: 50,
     }, this.config);

**Comment by stonko1994** [comment]
This is already tracked here: https://github.com/bitmovin/bitmovin-player-ui/issues/212
