### ISSUE TITLE
Update Bitmovin Player/Cast to V3

### ISSUE THREAD

**Issue by JorisvanW** [bitmovin/bitmovin-player-web-samples#37]
https://developers.google.com/cast/docs/migrate_v2/receiver

**Comment by vfernandes0408** [comment]
Do you have any update about this issue ?

**Comment by Milananas** [comment]
Also curious about this update, is it coming?

**Comment by dweinber** [comment]
This is definitely on the Roadmap, but unfortunately I can't share a timeline at the moment.

**Comment by dweinber** [comment]
This is currently being worked on and the initial release is planned for Q4 this year.

**Comment by aubert-creation** [comment]
Can we have a  CAF receiver exemple @dweinber

**Comment by dweinber** [comment]
Basic CAF support was introduced with 8.43.0.
A CAF receiver example can be found here now: https://github.com/bitmovin/bitmovin-player-caf-receiver
