### ISSUE TITLE
How do I add auto hide seeker bar and all button while video is playing?

### ISSUE THREAD

**Issue by temchannat** [bitmovin/bitmovin-player-web-samples#42]
I want to add close button and follow this [Link](https://github.com/bitmovin/bitmovin-player-android-samples/tree/master/CustomHtmlUi/src/main/assets) by @jarhoax . 
After added this, the seeker bar and all button is not auto hide when video is playing. How do I auto hide as default behavior?

**Comment by SInCE** [comment]
For further assistance please feel free to reach out to our support team as described here: https://github.com/bitmovin/bitmovin-player-android-samples#support 

Thank you very much for your understanding!
