### ISSUE TITLE
iOS OfflineManager cannot download mp4 file

### ISSUE THREAD

**Issue by temchannat** [bitmovin/bitmovin-player-web-samples#45]
I follow bitmovin [download link](https://bitmovin.com/docs/player/tutorials/offline-playback-with-the-bitmovin-ios-tvos-sdk) sample. I can download video with extension .m3u8, but the problem is I cannot play after downloading. I tried to download .mp4 file, but I cannot download. It return state for **notDownloaded**.

**Comment by DinaAminGad** [comment]
Hi @temchannat thanks for reaching out to us! 
May I ask which SDK link you used for the above?

**Comment by DinaAminGad** [comment]
In addition, please let me use this to introduce to you our support form which you can use it from https://bitmovin.com/dashboard/support/cases/create for an even better support experience :)
Looking forward to hear from you there!

**Comment by temchannat** [comment]
Hello @DinaAminGad,

The SDK version that I am using is 2.44.0.

**Comment by DinaAminGad** [comment]
Thanks a lot @temchannat for your update! Would you please open a ticket using https://bitmovin.com/dashboard/support/cases/create

**Comment by dweinber** [comment]
As this is not related to any of the samples of the web player, I'm going to close this issue. If your problem still persists, please open a support ticket here: https://bitmovin.com/dashboard/support/cases/create
